kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.processing.namespace }}
  generation: 1
  labels:
    app: {{ .Release.Name }}
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  serviceName: {{ .Release.Name }}-svc
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
        type: {{ .Values.processing.namespace }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
#        env:
#        livenessProbe:
#          tcpSocket:
#            port: 21
#          initialDelaySeconds: 30
#          periodSeconds: 30
#          timeoutSeconds: 5
#        volumeMounts:
#        -
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecrets }}
