cadip:
  inboxes:
    '1':
      path: /data
      retransfer: false
      stationUnitId: 123stationUnitId321
      acquisitionId: 54321
      antennaId: 54322
      frontEndId: 54323
  trigger:
    interval-ms: 120000

logging.level.de.werum.coprs.cadip.cadip_mock: DEBUG
server.address: 0.0.0.0